import { CAMPAIGNS } from '@/utils/constant'

export const CAMPAIGN_TYPE = {
  SMS: 1,
  EMAIL: 2,
  FCM: 3,
  VTF: 4
}

export const CAMPAIGN_LOG_TYPE = {
  UPDATE: 1,
  SENDING: 2,
  SENT: 3,
  SCHEDULE: 4
}

export const CAMPAIGN_LOG_MAP = new Map([
  [CAMPAIGNS.SENDING_CODE, CAMPAIGN_LOG_TYPE.SENDING],
  [CAMPAIGNS.SENT_CODE, CAMPAIGN_LOG_TYPE.SENT],
  [CAMPAIGNS.DRAFT_CODE, CAMPAIGN_LOG_TYPE.UPDATE],
  [CAMPAIGNS.SCHEDULED_CODE, CAMPAIGN_LOG_TYPE.SCHEDULE],
  ['default', CAMPAIGN_LOG_TYPE.UPDATE]
])

export const CAMPAIGN_STATUS = {
  SENDING: 1, SENT: 2, DRAFT: 3, SCHEDULED: 4
}
export const CAMPAIGN_SORT = {
  BY_CREATED_AT: 1, BY_UPDATED_AT: 2
}
export const CAMPAIGN_SENDING_STATUS = {
  SENT: 3,
  SENDING: 1,
  ERROR: 2
}

export const CAMPAIGN_SENDING_STATUS_MAP = new Map([
  [CAMPAIGN_SENDING_STATUS.SENT, 'Thành công'],
  [CAMPAIGN_SENDING_STATUS.SENDING, 'Đang gửi'],
  [CAMPAIGN_SENDING_STATUS.ERROR, 'Thất bại']
])
