export const ContactLogType = {
  ALL_ACTIVITY: 0,
  ADD: 1,
  IMPORT: 2,
  RECEIVE_MES_FROM_CAMPAIGN: 3,
  RECEIVE_MES_FROM_API: 4,
  OPEN_EMAIL: 5,
  CLICK_LINK_IN_EMAIL: 6

}

export const CONTACT_STATUS = {
  SUBSCRIBED: 1,
  NOT_YET_SUB: 2,
  ARCHIVED: 3
}

export const IMPORT_CONTACT_CONSTRAINT = {
  MAX_LENGTH_EMAIL: 200,
  MAX_LENGTH_PHONE: 20,
  MAX_LENGTH_FULLNAME: 200,
  MAX_LENGTH_ADDRESS: 500,
  MAX_LENGTH_TAG_NAME: 100,
  MAX_LENGTH_FIREBASE_KEY: 100,
  MAX_LENGTH_DEVICE_TOKEN: 100,
  MAX_LENGTH_EMPLOYEE_CODE: 50,
  MAX_LENGTH_FIREBASE_APPCODE: 50,
  MAX_LENGTH_DEVICE_NAME: 200
}

export const DEFAULT_EXPORT_FILE_NAME = 'Danh_sach_thue_bao';

