export const FIXED_FEATURE_ID = {
  SMS_SERVICE: 1,
  SMS_CAMPAIGN: 2,
  EMAIL_SERVICE: 3,
  EMAIL_CAMPAIGN: 4,
  FCM_SERVICE: 5,
  FCM_CAMPAIGN: 6
}

export const FEATURE_TYPES_MAP = new Map([
  [FIXED_FEATURE_ID.SMS_CAMPAIGN, 1],
  [FIXED_FEATURE_ID.SMS_SERVICE, 1],
  [FIXED_FEATURE_ID.EMAIL_CAMPAIGN, 2],
  [FIXED_FEATURE_ID.EMAIL_SERVICE, 2],
  [FIXED_FEATURE_ID.FCM_CAMPAIGN, 3],
  [FIXED_FEATURE_ID.FCM_SERVICE, 3]
]);
