export const INGREDIENT_INFO_TYPE = {
  BENEFIT: 1,
  WARNING_OVERUSE: 2,
  WARNING_CONSUMER: 3,
  WARNING_COMBINE: 4,
  TIP_SELECT: 5,
  TIP_PREPROCESS: 6,
  TIP_PRESERVE: 7
}

export const INGREDIENT_INFO_TYPE_BENEFIT_SHORT_TITLE = 'Lợi ích'
export const INGREDIENT_INFO_TYPE_WARNING_OVERUSE_SHORT_TITLE = 'Lạm dụng'
export const INGREDIENT_INFO_TYPE_WARNING_OVERUSE_SHORT_LONG_TITLE = 'Tác hại khi lạm dụng'
export const INGREDIENT_INFO_TYPE_WARNING_CONSUMER_SHORT_TITLE = 'Đối tượng'
export const INGREDIENT_INFO_TYPE_WARNING_CONSUMER_LONG_TITLE = 'Những đối tượng không nên dùng'
export const INGREDIENT_INFO_TYPE_WARNING_COMBINE_SHORT_TITLE = 'Kết hợp'
export const INGREDIENT_INFO_TYPE_WARNING_COMBINE_LONG_TITLE = 'Các thực phẩm không nên kết hợp'
export const INGREDIENT_INFO_TYPE_TIP_SELECT_SHORT_TITLE = 'Lựa chọn'
export const INGREDIENT_INFO_TYPE_TIP_PREPROCESS_SHORT_TITLE = 'Sơ chế'
export const INGREDIENT_INFO_TYPE_TIP_PRESERVE_SHORT_TITLE = 'Bảo quản'

export const INGREDIENT_INFO_TYPE_MAP = new Map([
  [INGREDIENT_INFO_TYPE.BENEFIT, INGREDIENT_INFO_TYPE_BENEFIT_SHORT_TITLE],
  [INGREDIENT_INFO_TYPE.WARNING_OVERUSE, INGREDIENT_INFO_TYPE_WARNING_OVERUSE_SHORT_TITLE],
  [INGREDIENT_INFO_TYPE.WARNING_CONSUMER, INGREDIENT_INFO_TYPE_WARNING_CONSUMER_SHORT_TITLE],
  [INGREDIENT_INFO_TYPE.WARNING_COMBINE, INGREDIENT_INFO_TYPE_WARNING_COMBINE_SHORT_TITLE],
  [INGREDIENT_INFO_TYPE.TIP_SELECT, INGREDIENT_INFO_TYPE_TIP_SELECT_SHORT_TITLE],
  [INGREDIENT_INFO_TYPE.TIP_PREPROCESS, INGREDIENT_INFO_TYPE_TIP_PREPROCESS_SHORT_TITLE],
  [INGREDIENT_INFO_TYPE.TIP_PRESERVE, INGREDIENT_INFO_TYPE_TIP_PRESERVE_SHORT_TITLE]
])

export const INGREDIENT_INFO_WARNING_TYPE_OPTIONS = [
  {
    label: INGREDIENT_INFO_TYPE_WARNING_OVERUSE_SHORT_TITLE,
    key: INGREDIENT_INFO_TYPE.WARNING_OVERUSE,
    value: INGREDIENT_INFO_TYPE.WARNING_OVERUSE
  },
  {
    label: INGREDIENT_INFO_TYPE_WARNING_CONSUMER_SHORT_TITLE,
    key: INGREDIENT_INFO_TYPE.WARNING_CONSUMER,
    value: INGREDIENT_INFO_TYPE.WARNING_CONSUMER
  },
  {
    label: INGREDIENT_INFO_TYPE_WARNING_COMBINE_SHORT_TITLE,
    key: INGREDIENT_INFO_TYPE.WARNING_COMBINE,
    value: INGREDIENT_INFO_TYPE.WARNING_COMBINE
  }
]

export const INGREDIENT_INFO_TIP_TYPE_OPTIONS = [
  {
    label: INGREDIENT_INFO_TYPE_TIP_SELECT_SHORT_TITLE,
    key: INGREDIENT_INFO_TYPE.TIP_SELECT,
    value: INGREDIENT_INFO_TYPE.TIP_SELECT
  },
  {
    label: INGREDIENT_INFO_TYPE_TIP_PREPROCESS_SHORT_TITLE,
    key: INGREDIENT_INFO_TYPE.TIP_PREPROCESS,
    value: INGREDIENT_INFO_TYPE.TIP_PREPROCESS
  },
  {
    label: INGREDIENT_INFO_TYPE_TIP_PRESERVE_SHORT_TITLE,
    key: INGREDIENT_INFO_TYPE.TIP_PRESERVE,
    value: INGREDIENT_INFO_TYPE.TIP_PRESERVE
  }
]
