export const AD_CATEGORY = {
  BOOK: { VALUE: 1, TITLE: 'Sách' },
  EDUCATION: { VALUE: 2, TITLE: 'Giáo dục' },
  TOOL: { VALUE: 3, TITLE: 'Công cụ' },
  EXERCISE_AND_HEALTH: { VALUE: 4, TITLE: 'Thể dục và sức khoẻ' },
  SPORT_AND_ENTERTAIN: { VALUE: 5, TITLE: 'Thể thao và giải trí' },
  FOOD_AND_DRINK: { VALUE: 6, TITLE: 'Ăn uống' },
  CAR_AND_VEHICLE: { VALUE: 7, TITLE: 'Xe cộ và phương tiện' },
  ENTERTAIN: { VALUE: 8, TITLE: 'Giải trí' },
  SHOPPING: { VALUE: 9, TITLE: 'Mua sắm' },
  TOURISM: { VALUE: 10, TITLE: 'Du lịch' },
  HOUSING_AND_GARDENING: { VALUE: 11, TITLE: 'Nhà cửa và làm vườn' },
  GAME: { VALUE: 12, TITLE: 'Trò chơi' },
  MEDICAL: { VALUE: 13, TITLE: 'Y tế' },
  REAL_ESTATE: { VALUE: 14, TITLE: 'Bất động sản' }
}

export const AD_CATEGORY_MAP = new Map([
  [AD_CATEGORY.BOOK.VALUE, AD_CATEGORY.BOOK.TITLE],
  [AD_CATEGORY.EDUCATION.VALUE, AD_CATEGORY.EDUCATION.TITLE],
  [AD_CATEGORY.TOOL.VALUE, AD_CATEGORY.TOOL.TITLE],
  [AD_CATEGORY.EXERCISE_AND_HEALTH.VALUE, AD_CATEGORY.EXERCISE_AND_HEALTH.TITLE],
  [AD_CATEGORY.SPORT_AND_ENTERTAIN.VALUE, AD_CATEGORY.SPORT_AND_ENTERTAIN.TITLE],
  [AD_CATEGORY.FOOD_AND_DRINK.VALUE, AD_CATEGORY.FOOD_AND_DRINK.TITLE],
  [AD_CATEGORY.CAR_AND_VEHICLE.VALUE, AD_CATEGORY.CAR_AND_VEHICLE.TITLE],
  [AD_CATEGORY.ENTERTAIN.VALUE, AD_CATEGORY.ENTERTAIN.TITLE],
  [AD_CATEGORY.SHOPPING.VALUE, AD_CATEGORY.SHOPPING.TITLE],
  [AD_CATEGORY.TOURISM.VALUE, AD_CATEGORY.TOURISM.TITLE],
  [AD_CATEGORY.HOUSING_AND_GARDENING.VALUE, AD_CATEGORY.HOUSING_AND_GARDENING.TITLE],
  [AD_CATEGORY.GAME.VALUE, AD_CATEGORY.GAME.TITLE],
  [AD_CATEGORY.MEDICAL.VALUE, AD_CATEGORY.MEDICAL.TITLE],
  [AD_CATEGORY.REAL_ESTATE.VALUE, AD_CATEGORY.REAL_ESTATE.TITLE]
])
